/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true,
    disableCaching: false
});

Ext.application({
    viewport: {
        itemId: 'viewport'
    },

    views: [
        'mainCanvasContainer',
        'fileSaveErrorCls',
        'fileSavedContainerCls',
        'fileSavingCls'
    ],
    name: 'MyApp',
    controllers: [
        'MyController'
    ],

    onViewportOrientationChange: function(viewport, newOrientation, width, height, options) {
        if( !ctx ) return;

        var m = Matrix();

        var cnv = document.getElementById("canv");
        var cnvCtx = cnv.getContext('2d');
        //var ccont = Ext.get("canvasBackground");
        var h = cnv.height;
        var w = cnv.width;

        // check if orient change is needed
        if( width > height && w > h || width < height && w < h ) return;
        h = width;
        // handle case when we see the resizing div
        // simulate cancel click + create again
        var restore = false;
        if( $('.ft-container').length==1 ){
            revertBtnAction();
            restore = true;
        }

        m = m.rotate(w>h?Math.PI/2:-Math.PI/2);
        var tmpCanv = document.createElement('canvas');
        tmpCanv.width = w;
        tmpCanv.height = h;
        var tmpCanvCtx = tmpCanv.getContext('2d');

        // rotate drawing canvas
        tmpCanvCtx.drawImage(cnv,0,0);
        cnvCtx.clearRect(0,0,cnv.width,cnv.height);
        cnv.width = h;
        cnv.height = w;

        cnvCtx.setTransform(m.a,m.b,m.c,m.d,w>h?h:0,w>h?0:w);
        cnvCtx.drawImage( tmpCanv , 0,0);
        cnvCtx.setTransform(1,0,0,1,0,0);

        // clear temp canvas
        tmpCanvCtx.clearRect(0,0,tmpCanv.width,tmpCanv.height);

        // now rotate bg canvas
        cnv = document.getElementById('bgcanv');
        tmpCanvCtx.drawImage(cnv,0,0);

        var bgCtx = cnv.getContext('2d');
        bgCtx.clearRect(0,0,cnv.width,cnv.height);
        cnv.width = h;
        cnv.height = w;

        bgCtx.setTransform(m.a,m.b,m.c,m.d,w>h?h:0,w>h?0:w);
        bgCtx.drawImage( tmpCanv , 0,0);
        bgCtx.setTransform(1,0,0,1,0,0);

        var disabler = document.getElementById('canvasDisabler');
        disabler.style.width = h  + "px";
        disabler.style.height = w + "px";

        var disablerTxt = document.getElementById('canvasDisablerChild');
        disablerTxt.style.width  = h + "px";
        disablerTxt.style.height = w + "px";

        if( restore ) btnAction();
    },

    launch: function() {
        //Ext.Ajax.setDisableCaching(false);
        console.log('launch');
        Ext.override(Ext.LoadMask, {
            getTemplate: function() {
                var prefix = Ext.baseCSSPrefix;

                return [
                {
                    //it needs an inner so it can be centered within the mask, and have a background
                    reference: 'innerElement',
                    cls: prefix + 'mask-inner',
                    children: [
                    //the elements required for the CSS loading {@link #indicator}
                    {
                        html: '<img src="logo.PNG"/>'
                    },
                    {
                        reference: 'indicatorElement',
                        cls: prefix + 'loading-spinner-outer',
                        children: [
                        {
                            cls: prefix + 'loading-spinner',
                            children: [
                            { tag: 'span', cls: prefix + 'loading-top' },
                            { tag: 'span', cls: prefix + 'loading-right' },
                            { tag: 'span', cls: prefix + 'loading-bottom' },
                            { tag: 'span', cls: prefix + 'loading-left' }
                            ]
                        }
                        ]
                    },
                    //the element used to display the {@link #message}
                    {
                        reference: 'messageElement'
                    }
                    ]
                }
                ];
            }
        });   


        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: 'Initializing'
        });

        Ext.Viewport.on([
        {
            event: 'orientationchange',
            fn: 'onViewportOrientationChange',
            scope: this
        }
        ]);
        Ext.create('MyApp.view.mainCanvasContainer', {fullscreen: true});
    }

});
