/*
 * File: app/view/fileSavedContainerCls.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.fileSavedContainerCls', {
    extend: 'Ext.Container',

    config: {
        id: 'fileSavedContainer',
        items: [
            {
                xtype: 'label',
                html: '<div style="text-align:center;font-size:200%">File saved to IMGUR!</div>',
                top: '30%',
                width: '100%'
            },
            {
                xtype: 'textfield',
                id: 'urlField',
                top: '50%',
                width: '100%',
                label: 'URL:',
                readOnly: true
            },
            {
                xtype: 'button',
                bottom: '',
                docked: 'bottom',
                itemId: 'mybutton11',
                ui: 'confirm',
                text: 'OK'
            },
            {
                xtype: 'button',
                docked: 'bottom',
                height: 10,
                itemId: 'mybutton13',
                text: 'GO TO URL'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton11Tap',
                event: 'tap',
                delegate: '#mybutton11'
            },
            {
                fn: 'onMybutton13Tap',
                event: 'tap',
                delegate: '#mybutton13'
            }
        ]
    },

    onMybutton11Tap: function(button, e, options) {
        Ext.Viewport.setActiveItem(Ext.getCmp('mainCanvasContainer'));
    },

    onMybutton13Tap: function(button, e, options) {
        window.open(Ext.getCmp('urlField').getValue());
    }

});