/*
 * File: app/view/fileSaveErrorCls.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.fileSaveErrorCls', {
    extend: 'Ext.Container',

    config: {
        cls: [
            'bgMsg'
        ],
        items: [
            {
                xtype: 'label',
                html: '<div style="text-align:center;font-size:200%">Error saving file</div>',
                top: '50%',
                width: '100%'
            },
            {
                xtype: 'button',
                docked: 'bottom',
                itemId: 'mybutton12',
                ui: 'confirm',
                text: 'OK'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton12Tap',
                event: 'tap',
                delegate: '#mybutton12'
            }
        ]
    },

    onMybutton12Tap: function(button, e, options) {
        Ext.Viewport.setActiveItem(Ext.getCmp('mainCanvasContainer'));
    }

});