/*
 * File: app/view/mainCanvasContainer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mainCanvasContainer', {
    extend: 'Ext.Container',

    config: {
        html: '',
        id: 'mainCanvasContainer',
        style: 'background-color:#fafafa',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'container',
                height: '48px',
                id: 'upperMenu',
                itemId: 'upperMenu',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'btn_save',
                        height: 48,
                        id: 'saveBtn',
                        itemId: 'savebtn',
                        width: '20%',
                        iconMask: true,
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        cls: 'btn_clear',
                        height: 48,
                        id: 'clearBtn',
                        itemId: 'clearbtn',
                        width: '20%',
                        iconCls: '',
                        iconMask: true,
                        text: 'Clear'
                    },
                    {
                        xtype: 'button',
                        cls: 'btn_pen',
                        height: 48,
                        id: 'penBtn',
                        itemId: 'mybutton9',
                        width: '20%',
                        text: 'Pen'
                    },
                    {
                        xtype: 'button',
                        cls: 'btn_erase',
                        height: 48,
                        id: 'eraseBtn',
                        itemId: 'eraseBtn',
                        width: '20%',
                        iconMask: true,
                        text: 'Erase'
                    },
                    {
                        xtype: 'checkboxfield',
                        cls: [
                            'chkLabel'
                        ],
                        height: 48,
                        id: 'autoChkBox',
                        maxWidth: '',
                        width: '',
                        label: 'fast<br>mode',
                        labelCls: 'chkLabel',
                        labelWidth: 0,
                        labelWrap: true
                    }
                ]
            },
            {
                xtype: 'container',
                border: '',
                height: '100%',
                html: '<canvas id="bgcanv" style="position:absolute;z-index:5" >Sorry, no canvas support:(</canvas><canvas id="canv" style="position:absolute;z-index:8" >Sorry, no canvas support:(</canvas><div id="canvasDisabler" style="position:absolute;z-index=9;color:#fff;"><div id="canvasDisablerChild" style="display:table-cell;vertical-align:middle;text-align:center">Do you really want to erase your drawing?</div></div>',
                id: 'canvasBackground',
                itemId: 'mycontainer2',
                padding: 0,
                layout: {
                    type: 'fit'
                },
                modal: false
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: 36,
                hideAnimation: 'slideOut',
                id: 'btns',
                showAnimation: 'slideIn',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                scrollable: 'horizontal',
                items: [
                    {
                        xtype: 'button',
                        cls: 'lowerBtns',
                        id: 'btn0',
                        itemId: 'mybutton',
                        width: 150,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        cls: 'lowerBtns',
                        id: 'btn1',
                        itemId: 'mybutton1',
                        width: 150,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        cls: 'lowerBtns',
                        id: 'btn2',
                        itemId: 'mybutton2',
                        width: 150,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        cls: 'lowerBtns',
                        id: 'btn3',
                        itemId: 'mybutton3',
                        width: 150,
                        text: ''
                    },
                    {
                        xtype: 'button',
                        cls: 'lowerBtns',
                        id: 'btn4',
                        itemId: 'mybutton4',
                        width: 150,
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: '36px',
                hidden: true,
                hideAnimation: 'slideOut',
                id: 'okcancel',
                showAnimation: 'slideIn',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'okbutton',
                        itemId: 'okbutton',
                        ui: 'confirm',
                        width: '50%',
                        text: 'OK'
                    },
                    {
                        xtype: 'button',
                        id: 'cancelbtn',
                        itemId: 'cancelbtn',
                        ui: 'decline',
                        width: '50%',
                        text: 'CANCEL'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onSavebtnTap',
                event: 'tap',
                delegate: '#saveBtn'
            },
            {
                fn: 'onClearbtnTap',
                event: 'tap',
                delegate: '#clearBtn'
            },
            {
                fn: 'onPenTap',
                event: 'tap',
                delegate: '#penBtn'
            },
            {
                fn: 'onEraseBtnTap',
                event: 'tap',
                delegate: '#eraseBtn'
            },
            {
                fn: 'onContainerInitialize',
                event: 'initialize'
            },
            {
                fn: 'onFirstBtnTap',
                event: 'tap',
                delegate: '#btn0'
            },
            {
                fn: 'onSecondBtnTap',
                event: 'tap',
                delegate: '#btn1'
            },
            {
                fn: 'onThirdBtnTap',
                event: 'tap',
                delegate: '#btn2'
            },
            {
                fn: 'onFourthBtnTap',
                event: 'tap',
                delegate: '#btn3'
            },
            {
                fn: 'onFifthBtnTap',
                event: 'tap',
                delegate: '#btn4'
            },
            {
                fn: 'onOKBtnTap',
                event: 'tap',
                delegate: '#okbutton'
            },
            {
                fn: 'onCancelBtnTap',
                event: 'tap',
                delegate: '#cancelbtn'
            }
        ]
    },

    onSavebtnTap: function(button, e, options) {

        /*
        if( !ctx ) return;



        var m = Matrix();


        var cnv = document.getElementById("canv");
        var cnvCtx = cnv.getContext('2d');
        //var ccont = Ext.get("canvasBackground");
        var h = cnv.height;
        var w = cnv.width;

        // check if orient change is needed
        // if( width > height && w > h || width < height && w < h ) return;

        // handle case when we see the resizing div
        // simulate cancel click + create again
        var restore = false;
        if( $('.ft-container').length==1 ){
            revertBtnAction();
            restore = true;
        }

        m = m.rotate(w>h?Math.PI/2:-Math.PI/2);
        var tmpCanv = document.createElement('canvas');
        tmpCanv.width = w;
        tmpCanv.height = h;
        var tmpCanvCtx = tmpCanv.getContext('2d');

        // rotate drawing canvas
        tmpCanvCtx.drawImage(cnv,0,0);
        cnvCtx.clearRect(0,0,w,h);
        cnv.width = h;
        cnv.height = w;

        cnvCtx.setTransform(m.a,m.b,m.c,m.d,w>h?h:0,w>h?0:w);
        cnvCtx.drawImage( tmpCanv , 0,0);
        cnvCtx.setTransform(1,0,0,1,0,0);

        // clear temp canvas
        tmpCanvCtx.clearRect(0,0,w,h);

        // now rotate bg canvas
        cnv = document.getElementById('bgcanv');
        tmpCanvCtx.drawImage(cnv,0,0);

        var bgCtx = cnv.getContext('2d');
        bgCtx.clearRect(0,0,w,h);
        cnv.width = h;
        cnv.height = w;

        bgCtx.setTransform(m.a,m.b,m.c,m.d,w>h?h:0,w>h?0:w);
        bgCtx.drawImage( tmpCanv , 0,0);
        bgCtx.setTransform(1,0,0,1,0,0);

        var disabler = document.getElementById('canvasDisabler');
        disabler.style.width = w;
        disabler.style.height = h;

        if( restore ) btnAction();
        */


        var canvas = document.getElementById('bgcanv');
        var dataURL =  canvas.toDataURL('image/jpeg', 0.9).split(',')[1];
        Ext.getCmp('saveBtn').setText("Saving...");
        //Ext.Viewport.setActiveItem({xclass: 'MyApp.view.fileSavingCls'});
        //Ext.Viewport.setActiveItem(Ext.getCmp('mainCanvasContainer'));
        Ext.Viewport.setActiveItem({xclass: 'MyApp.view.fileSavingCls'});

        $.ajax({
            url: 'http://api.imgur.com/2/upload.json',
            type: 'POST',
            data: {
                type: 'base64',
                key: 'ee8c370e1c1bb90bcd721d8daa152d46',
                name: 'sketch.png',
                title: 'sketch enhancer image',
                caption: 'image',
                image: dataURL
            },
            dataType: 'json'
        }).success(function(data) {
            Ext.getCmp('saveBtn').setText('SAVED');
            Ext.getCmp('saveBtn').setText("Save");
            Ext.Viewport.setActiveItem({
                xclass: 'MyApp.view.fileSavedContainerCls'
            });
            Ext.getCmp('urlField').setValue(data['upload']['links']['imgur_page']);
        }).error(function() {
            Ext.getCmp('saveBtn').setText("Save");
            Ext.Viewport.setActiveItem({
                xclass: 'MyApp.view.fileSaveErrorCls'
            });
        });
    },

    onClearbtnTap: function(button, e, options) {
        if(!wasEverDrawn) return;

        disableCanvas(  true , "canvasContainer");
        Ext.getCmp('okbutton').setText('YES!');
        Ext.getCmp('cancelbtn').setText('NO');
        Ext.get('btns').hide();
        Ext.get('okcancel').show();
    },

    onPenTap: function(button, e, options) {
        setMainDrawingMode(0);
    },

    onEraseBtnTap: function(button, e, options) {
        setMainDrawingMode(1);
    },

    onContainerInitialize: function(component, options) {
        if( ctx ) return;
        cp = findPos( getCanv() );
        ctx = getCanv().getContext('2d');
        brushImage = new Image();
        brushImage.onload = initCompleted;
        brushImage.src = "brushb.png";

        var cnv = document.getElementById("canv");
        var ccont = Ext.get("canvasBackground");
        cnv.width = ccont.getWidth();
        cnv.height = ccont.getHeight();
        //ctx.fillStyle='rgba(0,0,0,0)';
        //ctx.clearRect(0,0,ccont.getWidth(),ccont.getHeight());

        cnv = document.getElementById('bgcanv');
        cnv.style.backgroundImage = "url('c0.jpg')";
        //cnv.style.backgroundSize = 
        //cnv.style.backgroundRepeat = "no-repeat";
        cnv.width = ccont.getWidth();
        cnv.height = ccont.getHeight();

        var disabler = document.getElementById('canvasDisabler');
        disabler.style.width  = ccont.getWidth()  + "px";
        disabler.style.height = ccont.getHeight() + "px";
        disabler.style.backgroundColor = "rgba(200,200,200,0.5)";
        var disablerTxt = document.getElementById('canvasDisablerChild');
        disablerTxt.style.width  = ccont.getWidth()  + "px";
        disablerTxt.style.height = ccont.getHeight() + "px";
        disablerTxt.style.fontSize = "200%";
        disablerTxt.style.color="#111";
        disabler.style.display = "none";
        disablerTxt.style.display = "none";

        // create freetrans thingie
        freeTransImg = document.createElement('div');

        var cnvCont = document.getElementById('mainCanvasContainer');
        cnvCont.appendChild( freeTransImg );
        var insideImg = document.createElement('img');
        freeTransImg.appendChild( insideImg );
        $(freeTransImg).hide();
        freeTransImg.style.zIndex = "50";
        freeTransImg.setAttribute("id","freeTransImg");
        //freeTransImg.style.position = "absolute";
        insideImg.setAttribute("id","freeTransInsideImg");

        Ext.getCmp('eraseBtn').setBadgeText("");
        Ext.getCmp('penBtn').setBadgeText("active");

    },

    onFirstBtnTap: function(button, e, options) {
        btnAction(0);
    },

    onSecondBtnTap: function(button, e, options) {
        btnAction(1);
    },

    onThirdBtnTap: function(button, e, options) {
        btnAction(2);
    },

    onFourthBtnTap: function(button, e, options) {
        btnAction(3);
    },

    onFifthBtnTap: function(button, e, options) {
        btnAction(4);
    },

    onOKBtnTap: function(button, e, options) {
        Ext.get('btns').show();
        Ext.get('okcancel').hide();

        if( canvasDisabled() ){
            var c = document.getElementById('canv');
            ctx.clearRect(0,0,c.width,c.height);
            c = document.getElementById('bgcanv');
            c.getContext('2d').clearRect(0,0,c.width,c.height);
            disableCanvas( false );
            wasDrawn = false;
            wasEverDrawn = false;
        }else applyBtnAction();
    },

    onCancelBtnTap: function(button, e, options) {
        Ext.get('btns').show();
        Ext.get('okcancel').hide();

        if( canvasDisabled() ){
            disableCanvas(false);
        }else revertBtnAction();
    }

});